name: Test

on:
  push:
  pull_request:

jobs:

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install ruff
      - run: ruff check --output-format=github .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, '3.x']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test] coverage[toml]
      - name: Run test suite
        run: |
          python -m coverage run -m pytest
      - name: Store coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.python-version }}
          path: .coverage.*
          if-no-files-found: ignore

  coverage:
    name: Report coverage
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install coverage[toml]
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-*
      
      - name: Combine coverage data
        run: |
          python -m coverage combine coverage-data-*
          python -m coverage xml
          python -m coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY

      - name: Upload Codecov report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
